/**
 * Printable grade documents.
 *
 * Renders the user's own data into a clean, self-contained HTML document and
 * prints it via a hidden iframe (so the browser's "Print / Save as PDF" dialog
 * produces a tidy page, isolated from the app's styles and dark mode).
 *
 * IMPORTANT: these are a personal-reference convenience copy of data the user
 * typed in — NOT official academic records. The disclaimer below is rendered
 * on every document and the wording must stay consistent with the in-app Terms
 * and Conditions and Privacy Policy.
 */
import {
    computeGwa,
    getAcademicHonor,
    getLatinHonor,
    HONOR_MIN_UNITS,
} from "@/lib/academic";
import type { Semester, Subject } from "@/types";

// ── Formatting helpers ───────────────────────────────────────────────────────
function escapeHtml(value: string): string {
    return value
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");
}

function formatGrade(grade: number): string {
    return grade.toFixed(2);
}

function formatUnits(units: number): string {
    return Number.isInteger(units) ? String(units) : units.toFixed(1);
}

function formatGwa(gwa: number | null): string {
    return gwa === null ? "—" : gwa.toFixed(3);
}

function formatToday(): string {
    return new Date().toLocaleDateString(undefined, {
        year: "numeric",
        month: "long",
        day: "numeric",
    });
}

// Order used to sort semesters chronologically (oldest first) in summaries.
const SEMESTER_ORDER: Record<string, number> = { First: 1, Second: 2, Third: 3 };

function sortChronologically(semesters: Semester[]): Semester[] {
    return [...semesters].sort((a, b) => {
        const aYear = parseInt(a.schoolYear.split("-")[0], 10) || 0;
        const bYear = parseInt(b.schoolYear.split("-")[0], 10) || 0;
        if (aYear !== bYear) return aYear - bYear;
        return (SEMESTER_ORDER[a.semester] ?? 0) - (SEMESTER_ORDER[b.semester] ?? 0);
    });
}

// ── HTML fragments ───────────────────────────────────────────────────────────
function subjectsTable(subjects: Subject[]): string {
    const rows = subjects
        .map(
            (s, i) => `
            <tr>
              <td class="num">${i + 1}</td>
              <td>${escapeHtml(s.code)}</td>
              <td>${escapeHtml(s.title)}</td>
              <td class="num">${formatUnits(s.units)}</td>
              <td class="num">${formatGrade(s.grade)}</td>
            </tr>`,
        )
        .join("");

    return `
        <table>
          <thead>
            <tr>
              <th class="num">#</th>
              <th>Code</th>
              <th>Subject</th>
              <th class="num">Units</th>
              <th class="num">Grade</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>`;
}

function honorPill(honor: string | null): string {
    return honor ? `<span class="honor">${escapeHtml(honor)}</span>` : "";
}

const DISCLAIMER = (appName: string) => `
    <div class="disclaimer">
      Generated by ${escapeHtml(appName)} on ${formatToday()} from data entered
      by the user. This document is for personal reference only — it is
      <strong>not</strong> an official academic record and is not issued,
      certified, or endorsed by any school, registrar, or other authority.
    </div>`;

function metaBlock(rows: Array<[string, string] | null>): string {
    const items = rows
        .filter((r): r is [string, string] => r !== null)
        .map(([label, value]) => `<div><span>${label}:</span> ${value}</div>`)
        .join("");
    return items ? `<div class="meta">${items}</div>` : "";
}

const STYLES = `
    * { box-sizing: border-box; }
    html, body { margin: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #111827;
      padding: 32px;
      line-height: 1.45;
    }
    .doc { max-width: 720px; margin: 0 auto; }
    .doc-header { border-bottom: 2px solid #111827; padding-bottom: 12px; margin-bottom: 16px; }
    .app-name { font-size: 11px; letter-spacing: .12em; text-transform: uppercase; color: #6b7280; margin: 0 0 4px; }
    .doc-title { font-size: 24px; font-weight: 800; margin: 0; }
    .meta { margin-top: 10px; font-size: 12.5px; color: #374151; display: flex; flex-wrap: wrap; gap: 4px 28px; }
    .meta span { color: #6b7280; }
    table { width: 100%; border-collapse: collapse; margin: 10px 0 4px; font-size: 12.5px; }
    th, td { border: 1px solid #d1d5db; padding: 6px 10px; text-align: left; vertical-align: top; }
    th { background: #f3f4f6; font-weight: 600; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    th.num { text-align: right; }
    .section { margin-top: 22px; }
    .section-title { font-size: 15px; font-weight: 700; margin: 0; }
    .summary { margin-top: 8px; font-size: 13px; display: flex; flex-wrap: wrap; align-items: center; gap: 6px 24px; }
    .summary strong { font-size: 15px; }
    .honor { display: inline-block; padding: 2px 12px; border: 1px solid #111827; border-radius: 999px; font-size: 12px; font-weight: 600; }
    .overall { margin-top: 24px; padding: 14px 16px; border: 1px solid #111827; border-radius: 10px; background: #f9fafb; }
    .overall .section-title { margin-bottom: 6px; }
    .disclaimer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #6b7280; line-height: 1.5; }
    @page { margin: 16mm 14mm; }
    @media print {
      body { padding: 0; }
      .doc { max-width: none; }
      .section, .overall, table, tr { break-inside: avoid; }
    }`;

function renderDocument(title: string, body: string): string {
    return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title)}</title>
    <style>${STYLES}</style>
  </head>
  <body>
    <div class="doc">${body}</div>
  </body>
</html>`;
}

// ── Printing ─────────────────────────────────────────────────────────────────
/**
 * Writes a self-contained HTML document into a hidden iframe and opens the
 * browser print dialog for it. The iframe is removed after printing (with a
 * long fallback so it never leaks if `afterprint` doesn't fire).
 */
function printHtmlDocument(html: string): void {
    if (typeof window === "undefined") return;

    const iframe = document.createElement("iframe");
    iframe.setAttribute("aria-hidden", "true");
    iframe.style.position = "fixed";
    iframe.style.right = "0";
    iframe.style.bottom = "0";
    iframe.style.width = "0";
    iframe.style.height = "0";
    iframe.style.border = "0";
    document.body.appendChild(iframe);

    const frameWin = iframe.contentWindow;
    const frameDoc = frameWin?.document;
    if (!frameWin || !frameDoc) {
        iframe.remove();
        return;
    }

    let cleaned = false;
    const cleanup = () => {
        if (cleaned) return;
        cleaned = true;
        // Defer slightly so we never tear down while the dialog is mid-open.
        window.setTimeout(() => {
            if (document.body.contains(iframe)) document.body.removeChild(iframe);
        }, 500);
    };

    frameWin.addEventListener("afterprint", cleanup);

    frameDoc.open();
    frameDoc.write(html);
    frameDoc.close();

    // Let the iframe lay out before printing.
    window.setTimeout(() => {
        try {
            frameWin.focus();
            frameWin.print();
        } catch (err) {
            console.error("[grade-report] print failed:", err);
            cleanup();
        }
    }, 100);

    // Hard fallback so the iframe is never leaked if `afterprint` never fires.
    window.setTimeout(cleanup, 60000);
}

// ── Public API ───────────────────────────────────────────────────────────────
export interface SemesterReportOptions {
    appName: string;
    studentName?: string | null;
    /** e.g. "First Semester, S.Y. 2025-2026". Omit for the current working set. */
    periodLabel?: string | null;
    subjects: Subject[];
}

/** Prints a one-semester report for the given subjects. */
export function printSemesterReport({
    appName,
    studentName,
    periodLabel,
    subjects,
}: SemesterReportOptions): void {
    const { gwa, totalUnits } = computeGwa(subjects);
    const honor =
        gwa !== null && totalUnits >= HONOR_MIN_UNITS ? getAcademicHonor(gwa) : null;

    const body = `
        <div class="doc-header">
          <p class="app-name">${escapeHtml(appName)}</p>
          <h1 class="doc-title">Semester Report</h1>
          ${metaBlock([
              periodLabel ? ["Period", escapeHtml(periodLabel)] : ["Period", "Current (unsaved) subjects"],
              studentName ? ["Name", escapeHtml(studentName)] : null,
          ])}
        </div>
        ${subjectsTable(subjects)}
        <div class="summary">
          <div><span>Total units:</span> <strong>${formatUnits(totalUnits)}</strong></div>
          <div><span>GWA:</span> <strong>${formatGwa(gwa)}</strong></div>
          ${honorPill(honor)}
        </div>
        ${DISCLAIMER(appName)}`;

    const title = periodLabel ? `Semester Report — ${periodLabel}` : "Semester Report";
    printHtmlDocument(renderDocument(title, body));
}

export interface AcademicSummaryOptions {
    appName: string;
    studentName?: string | null;
    semesters: Semester[];
}

/** Prints a summary of all saved semesters, with a cumulative GWA. */
export function printAcademicSummary({
    appName,
    studentName,
    semesters,
}: AcademicSummaryOptions): void {
    const ordered = sortChronologically(semesters);

    const sections = ordered
        .map((sem) => {
            const { gwa, totalUnits } = computeGwa(sem.subjects);
            const honor =
                gwa !== null && totalUnits >= HONOR_MIN_UNITS
                    ? getAcademicHonor(gwa)
                    : null;
            const label = `${escapeHtml(sem.semester)} Semester, S.Y. ${escapeHtml(sem.schoolYear)}`;
            return `
                <div class="section">
                  <h2 class="section-title">${label}</h2>
                  ${subjectsTable(sem.subjects)}
                  <div class="summary">
                    <div><span>Units:</span> <strong>${formatUnits(totalUnits)}</strong></div>
                    <div><span>GWA:</span> <strong>${formatGwa(gwa)}</strong></div>
                    ${honorPill(honor)}
                  </div>
                </div>`;
        })
        .join("");

    const allSubjects = ordered.flatMap((s) => s.subjects);
    const { gwa: overallGwa, totalUnits: overallUnits } = computeGwa(allSubjects);
    // Latin (graduation) honors for the cumulative standing — distinct from the
    // per-semester scholarship honors above.
    const overallHonor =
        overallGwa !== null && overallUnits >= HONOR_MIN_UNITS
            ? getLatinHonor(overallGwa)
            : null;

    const body = `
        <div class="doc-header">
          <p class="app-name">${escapeHtml(appName)}</p>
          <h1 class="doc-title">Academic Summary</h1>
          ${metaBlock([
              studentName ? ["Name", escapeHtml(studentName)] : null,
              ["Semesters", String(ordered.length)],
          ])}
        </div>
        ${sections}
        <div class="overall">
          <h2 class="section-title">Overall</h2>
          <div class="summary">
            <div><span>Total units:</span> <strong>${formatUnits(overallUnits)}</strong></div>
            <div><span>Cumulative GWA:</span> <strong>${formatGwa(overallGwa)}</strong></div>
            ${honorPill(overallHonor)}
          </div>
        </div>
        ${DISCLAIMER(appName)}`;

    printHtmlDocument(renderDocument("Academic Summary", body));
}
